### ISSUE TITLE
Potential hang when changing tx_power or frequency_mhz

### ISSUE THREAD

**Issue by applio** [adafruit/Adafruit_CircuitPython_RFM9x#22] opened 2019-03-15 23:55 UTC
Using the setter to change `tx_power` or `frequency_mhz` after using the radio to send a packet can result in an indefinite hang.  It is unknown if this similarly impacts updates to other registers on the radio.  To reproduce, try altering `tx_power` after having already sent packets.

If a fix to prevent such hangs is possible, that would be ideal.  If it turns out there is no solution other than first performing a reset, then this behavior should probably be documented.

**Comment by brentru** [comment] 2019-05-05 18:20
We were unable to reproduce this on a Feather M4 + RFM96 FeatherWing today. 

Setting `frequency_mhz`:
```
for freq in range(int(8150), int(9160), int(1)):
    print('MHZ: ', freq/10)
    rfm9x.frequency_mhz = freq/10
    rfm9x.send(bytes("Hello world!\r\n","utf-8"))
    time.sleep(0.1)
```

`tx_power` was set within its range to test as well.

Closing out, @applio: Please provide testing setup information if this still fails for you.

**Closed by brentru** 2019-05-05 18:20 UTC
